name: Training Pipeline

on:
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Start VM
        run: |
          az vm start \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --name ${{ secrets.VM_NAME }}

      - name: Wait for VM
        run: sleep 60

      - name: Run Training (SYNC)
        run: |
          az vm run-command invoke \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --name ${{ secrets.VM_NAME }} \
            --command-id RunShellScript \
            --scripts "
              VM_USERNAME='${{ secrets.VM_USERNAME }}'

              sudo -u \$VM_USERNAME bash -c '
                set -ex

                export VM_USERNAME=\"${{ secrets.VM_USERNAME }}\"
                export MONGODB_URI=\"${{ secrets.MONGODB_URI }}\"
                export AZURE_STORAGE_CONNECTION_STRING=\"${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}\"
                export AZURE_ARTIFACT_STORAGE_CONNECTION_STRING=\"${{ secrets.AZURE_ARTIFACT_STORAGE_CONNECTION_STRING }}\"
                export AZURE_BLOB_ARTIFACT_CONTAINER=\"${{ secrets.AZURE_BLOB_ARTIFACT_CONTAINER }}\"
                export AZURE_BLOB_MLFLOW_ARTIFACT_CONTAINER=\"${{ secrets.AZURE_BLOB_MLFLOW_ARTIFACT_CONTAINER }}\"
                export MLFLOW_TRACKING_URI=\"http://127.0.0.1:5000\"

                cd /home/\$VM_USERNAME/url-phishing-detection

                echo \"=== VERIFY FILES ===\"
                ls -la
                ls -la scripts || true

                echo \"=== SYNC REPO ===\"
                git fetch origin
                git reset --hard origin/main
                git clean -fd

                if [ ! -f scripts/train.sh ]; then
                  echo \"ERROR: train.sh not found\"
                  exit 1
                fi

                echo \"START TIME: \$(date)\"

                bash scripts/train.sh

                echo \"END TIME: \$(date)\"
              '
            "

      - name: Stop VM
        if: always()
        run: |
          az vm deallocate \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --name ${{ secrets.VM_NAME }}